
[[constraint]]
  branch = "master"
  name = "github.com/agl/ed25519"

[[constraint]]
  branch = "master"
  name = "github.com/badoux/checkmail"

[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/btclog"

[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/go-flags"

[[constraint]]
  branch = "master"
  name = "github.com/dajohi/goemail"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/decred/dcrd"

[[constraint]]
  branch = "master"
  name = "github.com/decred/dcrtime"

[[constraint]]
  branch = "master"
  name = "github.com/decred/dcrwallet"

[[constraint]]
  name = "github.com/gorilla/csrf"
  version = "1.5.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.5.0"

[[constraint]]
  name = "github.com/gorilla/sessions"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/jrick/logrotate"

[[constraint]]
  name = "github.com/kennygrant/sanitize"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/marcopeereboom/lockfile"

[[constraint]]
  name = "github.com/pmezard/go-difflib"
  version = "1.0.0"

[[constraint]]
  name = "github.com/robfig/cron"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/syndtr/goleveldb"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "github.com/subosito/norma"
